language: minimal

services:
- docker

stages:
- name: deploy
  if: branch = master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - secure: "D8zH2MPE2vB43E1jYpXTq09DtdNmsLEjucm6/K2ZK65Mdx7m0x2+iBDreNnqt9IRUYaDWKukOdAUM9A/9n/B9kDMXixFx94AKxjbzmkluJD3HaCJxPg4Z/6rXRLgj0OVxa+yMFhw6IcWhgsSnnWtDYmQDHVtm/eVV1AMb2U23JEaIJUseGo7jTgqkgwIKCZ5WAV/A+y55bdiAFSGG/8V2iQ9H0MPET2KRdnElpR8vIwml4o/kyGySFpkUrmzw8q9RnicX4vZWJBqy+1u3sox9Gv6k7IH27ZWXZ2wMxv5AhyR2JpLPmzI0v8EKaDR2DB5ySvorZJbpUgAh+2mGpPxYUmWdBc5eGD9PfmsceF7UxseD6pm7oTOCq1g2wAy5zc1SoSZAhKG9de3QldjvsVE15hLpb9jD6KW3ZpC6c7F8QM1V8U+10Vp0IT6g9jSjPFo7isGNJJ99CXdrzI1tk3syMGrW74YBAO/3O67x5dx6PEtyiT7zi7o0Dm+CQ5pnY3dLeO6ljC0pylmsGB9pdvuIkNhy3FJTP+URn0M3yiapG7bCtsBE66T0fOQiw6bZIsw2RVQxoOU2BfKbuGuMmd91l9mIiPe4PIU2yM9hZur67BAAwv5FRRUhM3fM4J7UW2Cv85Z2RQlyLfs9McsrRGwi/ATVYizw26uNyx24RmaiyU="

jobs:
  include:
    - stage: deploy
      script:
      - docker login -u csbronner -p $DOCKER_PASSWORD
      - export REPO=csbronner/gnet-dump
      - docker build -f Dockerfile -t $REPO:$COMMIT .
      - docker tag $REPO:$COMMIT $REPO:latest
      - docker push $REPO